In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
## Define the vocabulary size
voc_size=10000

In [4]:
one_hot_repr=[one_hot(words,voc_size) for words in sent]

In [5]:
one_hot_repr

[[6475, 3722, 2782, 5393],
 [6475, 3722, 2782, 5158],
 [6475, 7246, 2782, 5118],
 [6741, 6998, 9094, 2165, 5271],
 [6741, 6998, 9094, 2165, 6644],
 [1767, 6475, 9005, 2782, 8132],
 [2556, 7815, 5766, 2165]]

In [6]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences##to make sentences of same size
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length=8
embedded_doc=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_doc)

[[   0    0    0    0 6475 3722 2782 5393]
 [   0    0    0    0 6475 3722 2782 5158]
 [   0    0    0    0 6475 7246 2782 5118]
 [   0    0    0 6741 6998 9094 2165 5271]
 [   0    0    0 6741 6998 9094 2165 6644]
 [   0    0    0 1767 6475 9005 2782 8132]
 [   0    0    0    0 2556 7815 5766 2165]]


In [9]:
##featute representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
model.predict(embedded_doc)

2025-03-09 16:46:18.847111: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.


1/1 [==============================] - 0s 344ms/step


array([[[ 0.01915118,  0.04918906,  0.00562815,  0.01302594,
          0.01828934, -0.02566686, -0.04050507,  0.01233708,
         -0.02063151,  0.01925871],
        [ 0.01915118,  0.04918906,  0.00562815,  0.01302594,
          0.01828934, -0.02566686, -0.04050507,  0.01233708,
         -0.02063151,  0.01925871],
        [ 0.01915118,  0.04918906,  0.00562815,  0.01302594,
          0.01828934, -0.02566686, -0.04050507,  0.01233708,
         -0.02063151,  0.01925871],
        [ 0.01915118,  0.04918906,  0.00562815,  0.01302594,
          0.01828934, -0.02566686, -0.04050507,  0.01233708,
         -0.02063151,  0.01925871],
        [ 0.01790977,  0.0354487 ,  0.02009738, -0.00288899,
         -0.036514  , -0.01550596,  0.0406557 ,  0.03832909,
          0.00734239, -0.01759049],
        [ 0.02992383,  0.03222391, -0.01987218,  0.00765401,
          0.00833214,  0.027048  ,  0.00836905, -0.00685918,
         -0.00331007, -0.02444082],
        [-0.00731317,  0.00414555, -0.01505911,  0.0

In [14]:
embedded_doc[0]

array([   0,    0,    0,    0, 6475, 3722, 2782, 5393], dtype=int32)